// DO NOT MODIFY THIS FILE !!
// THIS FILE IS GENERATED BY './utils/icon-type-gen.js' DURING 'npm run icons:type-gen'

// tslint:disable:ordered-imports

import arrow_right_svg from '@assets/icons/arrow-right.svg';
import coins_chf_svg from '@assets/icons/coins-chf.svg';
import construction_svg from '@assets/icons/construction.svg';
import couch_svg from '@assets/icons/couch.svg';
import credit_svg from '@assets/icons/credit.svg';
import cross_gap_svg from '@assets/icons/cross-gap.svg';
import epidemic_svg from '@assets/icons/epidemic.svg';
import household_move_svg from '@assets/icons/household_move.svg';
import liability_svg from '@assets/icons/liability.svg';
import streaming_svg from '@assets/icons/streaming.svg';
import valuables_svg from '@assets/icons/valuables.svg';

export const localIcons = {
  'arrow-right': arrow_right_svg,
  'coins-chf': coins_chf_svg,
  construction: construction_svg,
  couch: couch_svg,
  credit: credit_svg,
  'cross-gap': cross_gap_svg,
  epidemic: epidemic_svg,
  household_move: household_move_svg,
  liability: liability_svg,
  streaming: streaming_svg,
  valuables: valuables_svg,
};
