// DO NOT MODIFY THIS FILE !!
// THIS FILE IS GENERATED BY './utils/icon-type-gen.js' DURING 'npm run icons:type-gen'

// tslint:disable:ordered-imports

import _24_x_7_svg from '@axa-ch/materials/images/_24-x-7.svg.js';
import accident_svg from '@axa-ch/materials/images/accident.svg.js';
import accidents_svg from '@axa-ch/materials/images/accidents.svg.js';
import activity_svg from '@axa-ch/materials/images/activity.svg.js';
import ads_svg from '@axa-ch/materials/images/ads.svg.js';
import agreement_svg from '@axa-ch/materials/images/agreement.svg.js';
import aircraft_svg from '@axa-ch/materials/images/aircraft.svg.js';
import allergy_svg from '@axa-ch/materials/images/allergy.svg.js';
import ambulance_svg from '@axa-ch/materials/images/ambulance.svg.js';
import amputation_svg from '@axa-ch/materials/images/amputation.svg.js';
import animal_stag_svg from '@axa-ch/materials/images/animal-stag.svg.js';
import apartment_block_svg from '@axa-ch/materials/images/apartment-block.svg.js';
import architect_svg from '@axa-ch/materials/images/architect.svg.js';
import arrow_positive_svg from '@axa-ch/materials/images/arrow-positive.svg.js';
import award_svg from '@axa-ch/materials/images/award.svg.js';
import axa_logo_svg from '@axa-ch/materials/images/axa-logo.svg.js';
import axa_logo_open_svg from '@axa-ch/materials/images/axa-logo-open.svg.js';
import baby_svg from '@axa-ch/materials/images/baby.svg.js';
import baby_sitting_svg from '@axa-ch/materials/images/baby-sitting.svg.js';
import back_pain_svg from '@axa-ch/materials/images/back-pain.svg.js';
import badge_svg from '@axa-ch/materials/images/badge.svg.js';
import bank_svg from '@axa-ch/materials/images/bank.svg.js';
import bank_dollar_svg from '@axa-ch/materials/images/bank-dollar.svg.js';
import bank_euro_svg from '@axa-ch/materials/images/bank-euro.svg.js';
import bank_pound_svg from '@axa-ch/materials/images/bank-pound.svg.js';
import bank_yen_svg from '@axa-ch/materials/images/bank-yen.svg.js';
import bills_dollar_svg from '@axa-ch/materials/images/bills-dollar.svg.js';
import bills_euro_svg from '@axa-ch/materials/images/bills-euro.svg.js';
import bills_pound_svg from '@axa-ch/materials/images/bills-pound.svg.js';
import bills_yen_svg from '@axa-ch/materials/images/bills-yen.svg.js';
import birthday_svg from '@axa-ch/materials/images/birthday.svg.js';
import book_svg from '@axa-ch/materials/images/book.svg.js';
import boy_svg from '@axa-ch/materials/images/boy.svg.js';
import breakdown_truck_svg from '@axa-ch/materials/images/breakdown-truck.svg.js';
import breakpoint_svg from '@axa-ch/materials/images/breakpoint.svg.js';
import broke_robot_svg from '@axa-ch/materials/images/broke-robot.svg.js';
import broken_bottle_svg from '@axa-ch/materials/images/broken-bottle.svg.js';
import broken_glass_svg from '@axa-ch/materials/images/broken-glass.svg.js';
import building_svg from '@axa-ch/materials/images/building.svg.js';
import building_1_svg from '@axa-ch/materials/images/building-1.svg.js';
import cabriolet_svg from '@axa-ch/materials/images/cabriolet.svg.js';
import calculator_svg from '@axa-ch/materials/images/calculator.svg.js';
import calendar_svg from '@axa-ch/materials/images/calendar.svg.js';
import camping_car_svg from '@axa-ch/materials/images/camping-car.svg.js';
import cancelation_svg from '@axa-ch/materials/images/cancelation.svg.js';
import cancellation_svg from '@axa-ch/materials/images/cancellation.svg.js';
import cancellation_1_svg from '@axa-ch/materials/images/cancellation_1.svg.js';
import car_svg from '@axa-ch/materials/images/car.svg.js';
import car_hail_svg from '@axa-ch/materials/images/car-hail.svg.js';
import car_substitution_svg from '@axa-ch/materials/images/car-substitution.svg.js';
import caravan_svg from '@axa-ch/materials/images/caravan.svg.js';
import carelessness_svg from '@axa-ch/materials/images/carelessness.svg.js';
import cars_svg from '@axa-ch/materials/images/cars.svg.js';
import castel_svg from '@axa-ch/materials/images/castel.svg.js';
import chair_svg from '@axa-ch/materials/images/chair.svg.js';
import change_investments_svg from '@axa-ch/materials/images/change-investments.svg.js';
import channeling_svg from '@axa-ch/materials/images/channeling.svg.js';
import chat_bubble_svg from '@axa-ch/materials/images/chat-bubble.svg.js';
import chat_men_svg from '@axa-ch/materials/images/chat-men.svg.js';
import chat_woman_svg from '@axa-ch/materials/images/chat-woman.svg.js';
import check_list_svg from '@axa-ch/materials/images/check-list.svg.js';
import cigarette_svg from '@axa-ch/materials/images/cigarette.svg.js';
import citycar_svg from '@axa-ch/materials/images/citycar.svg.js';
import climate_event_svg from '@axa-ch/materials/images/climate-event.svg.js';
import clock_svg from '@axa-ch/materials/images/clock.svg.js';
import cocktail_svg from '@axa-ch/materials/images/cocktail.svg.js';
import coffee_machine_svg from '@axa-ch/materials/images/coffee-machine.svg.js';
import coins_svg from '@axa-ch/materials/images/coins.svg.js';
import coins_dollar_svg from '@axa-ch/materials/images/coins-dollar.svg.js';
import coins_euro_svg from '@axa-ch/materials/images/coins-euro.svg.js';
import coins_pound_svg from '@axa-ch/materials/images/coins-pound.svg.js';
import coins_yen_svg from '@axa-ch/materials/images/coins-yen.svg.js';
import company_svg from '@axa-ch/materials/images/company.svg.js';
import computer_secure_svg from '@axa-ch/materials/images/computer-secure.svg.js';
import consturction_svg from '@axa-ch/materials/images/consturction.svg.js';
import contamination_svg from '@axa-ch/materials/images/contamination.svg.js';
import contract_svg from '@axa-ch/materials/images/contract.svg.js';
import contract_termination_svg from '@axa-ch/materials/images/contract-termination.svg.js';
import contractor_svg from '@axa-ch/materials/images/contractor.svg.js';
import conversation_svg from '@axa-ch/materials/images/conversation.svg.js';
import corrupt_file_svg from '@axa-ch/materials/images/corrupt-file.svg.js';
import credit_card_svg from '@axa-ch/materials/images/credit-card.svg.js';
import critical_illness_svg from '@axa-ch/materials/images/critical-illness.svg.js';
import custody_svg from '@axa-ch/materials/images/custody.svg.js';
import danger_svg from '@axa-ch/materials/images/danger.svg.js';
import death_svg from '@axa-ch/materials/images/death.svg.js';
import dental_svg from '@axa-ch/materials/images/dental.svg.js';
import desk_svg from '@axa-ch/materials/images/desk.svg.js';
import desktop_svg from '@axa-ch/materials/images/desktop.svg.js';
import doctor_man_svg from '@axa-ch/materials/images/doctor-man.svg.js';
import doctor_woman_svg from '@axa-ch/materials/images/doctor-woman.svg.js';
import document_svg from '@axa-ch/materials/images/document.svg.js';
import dog_svg from '@axa-ch/materials/images/dog.svg.js';
import download_svg from '@axa-ch/materials/images/download.svg.js';
import electric_car_svg from '@axa-ch/materials/images/electric-car.svg.js';
import electric_damages_svg from '@axa-ch/materials/images/electric-damages.svg.js';
import electric_repairing_svg from '@axa-ch/materials/images/electric-repairing.svg.js';
import elevator_svg from '@axa-ch/materials/images/elevator.svg.js';
import employee_svg from '@axa-ch/materials/images/employee.svg.js';
import employee_hire_svg from '@axa-ch/materials/images/employee-hire.svg.js';
import employee_retired_svg from '@axa-ch/materials/images/employee-retired.svg.js';
import employee_transition_svg from '@axa-ch/materials/images/employee-transition.svg.js';
import environment_svg from '@axa-ch/materials/images/environment.svg.js';
import extractor_hood_svg from '@axa-ch/materials/images/extractor-hood.svg.js';
import eye_svg from '@axa-ch/materials/images/eye.svg.js';
import eye_1_svg from '@axa-ch/materials/images/eye_1.svg.js';
import facebook_svg from '@axa-ch/materials/images/facebook.svg.js';
import family_svg from '@axa-ch/materials/images/family.svg.js';
import family_g_svg from '@axa-ch/materials/images/family-g.svg.js';
import family_l_svg from '@axa-ch/materials/images/family-l.svg.js';
import family_single_f_svg from '@axa-ch/materials/images/family-single-f.svg.js';
import family_single_m_svg from '@axa-ch/materials/images/family-single-m.svg.js';
import farm_svg from '@axa-ch/materials/images/farm.svg.js';
import fax_svg from '@axa-ch/materials/images/fax.svg.js';
import financial_loss_svg from '@axa-ch/materials/images/financial-loss.svg.js';
import financial_loss_2_svg from '@axa-ch/materials/images/financial-loss-2.svg.js';
import finger_print_svg from '@axa-ch/materials/images/finger-print.svg.js';
import fire_svg from '@axa-ch/materials/images/fire.svg.js';
import fire_house_svg from '@axa-ch/materials/images/fire-house.svg.js';
import fishing_svg from '@axa-ch/materials/images/fishing.svg.js';
import flood_house_svg from '@axa-ch/materials/images/flood-house.svg.js';
import floor_svg from '@axa-ch/materials/images/floor.svg.js';
import food_poisoning_svg from '@axa-ch/materials/images/food-poisoning.svg.js';
import frost_svg from '@axa-ch/materials/images/frost.svg.js';
import fryer_svg from '@axa-ch/materials/images/fryer.svg.js';
import furniture_svg from '@axa-ch/materials/images/furniture.svg.js';
import garage_svg from '@axa-ch/materials/images/garage.svg.js';
import gauge_svg from '@axa-ch/materials/images/gauge.svg.js';
import gear_svg from '@axa-ch/materials/images/gear.svg.js';
import gear_2_svg from '@axa-ch/materials/images/gear-2.svg.js';
import gender_svg from '@axa-ch/materials/images/gender.svg.js';
import glas_vitrine_svg from '@axa-ch/materials/images/glas-vitrine.svg.js';
import global_svg from '@axa-ch/materials/images/global.svg.js';
import glossary_svg from '@axa-ch/materials/images/glossary.svg.js';
import goods_transport_svg from '@axa-ch/materials/images/goods-transport.svg.js';
import graduation_hat_svg from '@axa-ch/materials/images/graduation-hat.svg.js';
import greenhouse_svg from '@axa-ch/materials/images/greenhouse.svg.js';
import growth_svg from '@axa-ch/materials/images/growth.svg.js';
import growth_dollar_svg from '@axa-ch/materials/images/growth-dollar.svg.js';
import growth_euro_svg from '@axa-ch/materials/images/growth-euro.svg.js';
import growth_pound_svg from '@axa-ch/materials/images/growth-pound.svg.js';
import growth_yen_svg from '@axa-ch/materials/images/growth-yen.svg.js';
import hand_cross_svg from '@axa-ch/materials/images/hand-cross.svg.js';
import hand_heart_svg from '@axa-ch/materials/images/hand-heart.svg.js';
import hand_leaf_svg from '@axa-ch/materials/images/hand-leaf.svg.js';
import health_kit_svg from '@axa-ch/materials/images/health-kit.svg.js';
import hearing_impaired_svg from '@axa-ch/materials/images/hearing-impaired.svg.js';
import heart_svg from '@axa-ch/materials/images/heart.svg.js';
import heater_svg from '@axa-ch/materials/images/heater.svg.js';
import help_svg from '@axa-ch/materials/images/help.svg.js';
import help_man_svg from '@axa-ch/materials/images/help-man.svg.js';
import help_woman_svg from '@axa-ch/materials/images/help-woman.svg.js';
import hospital_svg from '@axa-ch/materials/images/hospital.svg.js';
import hospital_bed_svg from '@axa-ch/materials/images/hospital-bed.svg.js';
import hotel_bed_svg from '@axa-ch/materials/images/hotel-bed.svg.js';
import hotel_reception_woman_svg from '@axa-ch/materials/images/hotel-reception-woman.svg.js';
import house_svg from '@axa-ch/materials/images/house.svg.js';
import idcard_svg from '@axa-ch/materials/images/idcard.svg.js';
import inbox_svg from '@axa-ch/materials/images/inbox.svg.js';
import industry_svg from '@axa-ch/materials/images/industry.svg.js';
import inflammable_liquid_svg from '@axa-ch/materials/images/inflammable-liquid.svg.js';
import injection_svg from '@axa-ch/materials/images/injection.svg.js';
import instagram_svg from '@axa-ch/materials/images/instagram.svg.js';
import it_vpn_svg from '@axa-ch/materials/images/it-vpn.svg.js';
import keys_svg from '@axa-ch/materials/images/keys.svg.js';
import laptop_repair_svg from '@axa-ch/materials/images/laptop-repair.svg.js';
import legal_svg from '@axa-ch/materials/images/legal.svg.js';
import legal_services_svg from '@axa-ch/materials/images/legal-services.svg.js';
import light_bulb_svg from '@axa-ch/materials/images/light-bulb.svg.js';
import linkedin_svg from '@axa-ch/materials/images/linkedin.svg.js';
import living_with_parents_svg from '@axa-ch/materials/images/living-with-parents.svg.js';
import location_image_svg from '@axa-ch/materials/images/location-image.svg.js';
import magnifer_glass_svg from '@axa-ch/materials/images/magnifer-glass.svg.js';
import mail_svg from '@axa-ch/materials/images/mail.svg.js';
import major_crisis_svg from '@axa-ch/materials/images/major-crisis.svg.js';
import man_elderly_svg from '@axa-ch/materials/images/man-elderly.svg.js';
import man_tie_svg from '@axa-ch/materials/images/man-tie.svg.js';
import man_woman_svg from '@axa-ch/materials/images/man-woman.svg.js';
import map__pin_locator_svg from '@axa-ch/materials/images/map--pin-locator.svg.js';
import matchstick_svg from '@axa-ch/materials/images/matchstick.svg.js';
import medal_svg from '@axa-ch/materials/images/medal.svg.js';
import medical_assistance_svg from '@axa-ch/materials/images/medical-assistance.svg.js';
import men_svg from '@axa-ch/materials/images/men.svg.js';
import mental_disability_svg from '@axa-ch/materials/images/mental-disability.svg.js';
import merchandise_svg from '@axa-ch/materials/images/merchandise.svg.js';
import microwave_svg from '@axa-ch/materials/images/microwave.svg.js';
import mindset_svg from '@axa-ch/materials/images/mindset.svg.js';
import mobile_svg from '@axa-ch/materials/images/mobile.svg.js';
import mobile_home_svg from '@axa-ch/materials/images/mobile-home.svg.js';
import moped_svg from '@axa-ch/materials/images/moped.svg.js';
import more_svg from '@axa-ch/materials/images/more.svg.js';
import motor_disability_svg from '@axa-ch/materials/images/motor-disability.svg.js';
import motorcycle_svg from '@axa-ch/materials/images/motorcycle.svg.js';
import mpv_svg from '@axa-ch/materials/images/mpv.svg.js';
import newspaper_svg from '@axa-ch/materials/images/newspaper.svg.js';
import note_pen_svg from '@axa-ch/materials/images/note-pen.svg.js';
import number_of_rooms_svg from '@axa-ch/materials/images/number-of-rooms.svg.js';
import nutrition_svg from '@axa-ch/materials/images/nutrition.svg.js';
import on_board_device_svg from '@axa-ch/materials/images/on-board-device.svg.js';
import optical_svg from '@axa-ch/materials/images/optical.svg.js';
import organization_svg from '@axa-ch/materials/images/organization.svg.js';
import padlock_svg from '@axa-ch/materials/images/padlock.svg.js';
import paint_roll_svg from '@axa-ch/materials/images/paint-roll.svg.js';
import pan_svg from '@axa-ch/materials/images/pan.svg.js';
import parking_svg from '@axa-ch/materials/images/parking.svg.js';
import penalty_svg from '@axa-ch/materials/images/penalty.svg.js';
import pet_svg from '@axa-ch/materials/images/pet.svg.js';
import phone_svg from '@axa-ch/materials/images/phone.svg.js';
import pie_chart_svg from '@axa-ch/materials/images/pie-chart.svg.js';
import piggy_bank_svg from '@axa-ch/materials/images/piggy-bank.svg.js';
import pin_locator_svg from '@axa-ch/materials/images/pin-locator.svg.js';
import plane_svg from '@axa-ch/materials/images/plane.svg.js';
import plaster_crutch_svg from '@axa-ch/materials/images/plaster-crutch.svg.js';
import play_svg from '@axa-ch/materials/images/play.svg.js';
import plug_svg from '@axa-ch/materials/images/plug.svg.js';
import plug_adaptor_svg from '@axa-ch/materials/images/plug-adaptor.svg.js';
import plus_svg from '@axa-ch/materials/images/plus.svg.js';
import power_button_svg from '@axa-ch/materials/images/power-button.svg.js';
import print_svg from '@axa-ch/materials/images/print.svg.js';
import private_mansion_svg from '@axa-ch/materials/images/private-mansion.svg.js';
import psychological_disability_svg from '@axa-ch/materials/images/psychological-disability.svg.js';
import public_liability_svg from '@axa-ch/materials/images/public-liability.svg.js';
import puzzle_svg from '@axa-ch/materials/images/puzzle.svg.js';
import questionmark_svg from '@axa-ch/materials/images/questionmark.svg.js';
import radio_svg from '@axa-ch/materials/images/radio.svg.js';
import reffrigerator_svg from '@axa-ch/materials/images/reffrigerator.svg.js';
import register_svg from '@axa-ch/materials/images/register.svg.js';
import remote_control_svg from '@axa-ch/materials/images/remote-control.svg.js';
import repair_2_svg from '@axa-ch/materials/images/repair-2.svg.js';
import repairs_svg from '@axa-ch/materials/images/repairs.svg.js';
import repairs_2_svg from '@axa-ch/materials/images/repairs-2.svg.js';
import restaurant_svg from '@axa-ch/materials/images/restaurant.svg.js';
import ring_svg from '@axa-ch/materials/images/ring.svg.js';
import road_safety_svg from '@axa-ch/materials/images/road-safety.svg.js';
import rocking_chair_svg from '@axa-ch/materials/images/rocking-chair.svg.js';
import safe_svg from '@axa-ch/materials/images/safe.svg.js';
import safety_belt_svg from '@axa-ch/materials/images/safety-belt.svg.js';
import sail_boat_svg from '@axa-ch/materials/images/sail-boat.svg.js';
import salooncar_svg from '@axa-ch/materials/images/salooncar.svg.js';
import sanitary_svg from '@axa-ch/materials/images/sanitary.svg.js';
import saving_yen_svg from '@axa-ch/materials/images/saving-yen.svg.js';
import savings_dollar_svg from '@axa-ch/materials/images/savings-dollar.svg.js';
import savings_euro_svg from '@axa-ch/materials/images/savings-euro.svg.js';
import savings_pound_svg from '@axa-ch/materials/images/savings-pound.svg.js';
import security_cam_svg from '@axa-ch/materials/images/security-cam.svg.js';
import share_svg from '@axa-ch/materials/images/share.svg.js';
import shield_svg from '@axa-ch/materials/images/shield.svg.js';
import shopping_trolley_svg from '@axa-ch/materials/images/shopping-trolley.svg.js';
import sickness_svg from '@axa-ch/materials/images/sickness.svg.js';
import site_foreman_svg from '@axa-ch/materials/images/site-foreman.svg.js';
import ski_svg from '@axa-ch/materials/images/ski.svg.js';
import software_svg from '@axa-ch/materials/images/software.svg.js';
import solar_panel_svg from '@axa-ch/materials/images/solar-panel.svg.js';
import solid_construction_svg from '@axa-ch/materials/images/solid-construction.svg.js';
import sports_equipment_svg from '@axa-ch/materials/images/sports-equipment.svg.js';
import store_svg from '@axa-ch/materials/images/store.svg.js';
import strethoscope_svg from '@axa-ch/materials/images/strethoscope.svg.js';
import suitcase_svg from '@axa-ch/materials/images/suitcase.svg.js';
import suitcase_1_svg from '@axa-ch/materials/images/suitcase_1.svg.js';
import sun_svg from '@axa-ch/materials/images/sun.svg.js';
import suv_svg from '@axa-ch/materials/images/suv.svg.js';
import swiss_svg from '@axa-ch/materials/images/swiss.svg.js';
import symbol_dollar_svg from '@axa-ch/materials/images/symbol-dollar.svg.js';
import symbol_euro_svg from '@axa-ch/materials/images/symbol-euro.svg.js';
import symbol_pounds_svg from '@axa-ch/materials/images/symbol-pounds.svg.js';
import symbol_yen_svg from '@axa-ch/materials/images/symbol-yen.svg.js';
import tablet_svg from '@axa-ch/materials/images/tablet.svg.js';
import target_svg from '@axa-ch/materials/images/target.svg.js';
import taxi_svg from '@axa-ch/materials/images/taxi.svg.js';
import theft_svg from '@axa-ch/materials/images/theft.svg.js';
import thumb_svg from '@axa-ch/materials/images/thumb.svg.js';
import tick_svg from '@axa-ch/materials/images/tick.svg.js';
import time_svg from '@axa-ch/materials/images/time.svg.js';
import tools_svg from '@axa-ch/materials/images/tools.svg.js';
import town_hall_svg from '@axa-ch/materials/images/town-hall.svg.js';
import tractor_svg from '@axa-ch/materials/images/tractor.svg.js';
import travel_case_svg from '@axa-ch/materials/images/travel-case.svg.js';
import twitter_svg from '@axa-ch/materials/images/twitter.svg.js';
import umbrella_svg from '@axa-ch/materials/images/umbrella.svg.js';
import upload_svg from '@axa-ch/materials/images/upload.svg.js';
import usage_type_house_svg from '@axa-ch/materials/images/usage-type-house.svg.js';
import van_svg from '@axa-ch/materials/images/van.svg.js';
import ventilation_svg from '@axa-ch/materials/images/ventilation.svg.js';
import vine_svg from '@axa-ch/materials/images/vine.svg.js';
import warehouse_fire_svg from '@axa-ch/materials/images/warehouse-fire.svg.js';
import warenhouse_svg from '@axa-ch/materials/images/warenhouse.svg.js';
import washing_machine_svg from '@axa-ch/materials/images/washing-machine.svg.js';
import water_can_svg from '@axa-ch/materials/images/water-can.svg.js';
import water_damage_svg from '@axa-ch/materials/images/water-damage.svg.js';
import wc_svg from '@axa-ch/materials/images/wc.svg.js';
import weather_warning_svg from '@axa-ch/materials/images/weather-warning.svg.js';
import wechat_svg from '@axa-ch/materials/images/wechat.svg.js';
import wheat_svg from '@axa-ch/materials/images/wheat.svg.js';
import wheelchair_svg from '@axa-ch/materials/images/wheelchair.svg.js';
import wheelchair_man_svg from '@axa-ch/materials/images/wheelchair-man.svg.js';
import wind_turbine_svg from '@axa-ch/materials/images/wind-turbine.svg.js';
import within_1_hrs_svg from '@axa-ch/materials/images/within-1-hrs.svg.js';
import within_24_hrs_svg from '@axa-ch/materials/images/within-24-hrs.svg.js';
import within_72_hrs_svg from '@axa-ch/materials/images/within-72-hrs.svg.js';
import woman_svg from '@axa-ch/materials/images/woman.svg.js';
import woman_elderly_svg from '@axa-ch/materials/images/woman-elderly.svg.js';
import woman_shirt_svg from '@axa-ch/materials/images/woman-shirt.svg.js';
import world_svg from '@axa-ch/materials/images/world.svg.js';
import youtube_svg from '@axa-ch/materials/images/youtube.svg.js';

export const plImages = {
  '_24-x-7': _24_x_7_svg,
  accident: accident_svg,
  accidents: accidents_svg,
  activity: activity_svg,
  ads: ads_svg,
  agreement: agreement_svg,
  aircraft: aircraft_svg,
  allergy: allergy_svg,
  ambulance: ambulance_svg,
  amputation: amputation_svg,
  'animal-stag': animal_stag_svg,
  'apartment-block': apartment_block_svg,
  architect: architect_svg,
  'arrow-positive': arrow_positive_svg,
  award: award_svg,
  'axa-logo': axa_logo_svg,
  'axa-logo-open': axa_logo_open_svg,
  baby: baby_svg,
  'baby-sitting': baby_sitting_svg,
  'back-pain': back_pain_svg,
  badge: badge_svg,
  bank: bank_svg,
  'bank-dollar': bank_dollar_svg,
  'bank-euro': bank_euro_svg,
  'bank-pound': bank_pound_svg,
  'bank-yen': bank_yen_svg,
  'bills-dollar': bills_dollar_svg,
  'bills-euro': bills_euro_svg,
  'bills-pound': bills_pound_svg,
  'bills-yen': bills_yen_svg,
  birthday: birthday_svg,
  book: book_svg,
  boy: boy_svg,
  'breakdown-truck': breakdown_truck_svg,
  breakpoint: breakpoint_svg,
  'broke-robot': broke_robot_svg,
  'broken-bottle': broken_bottle_svg,
  'broken-glass': broken_glass_svg,
  building: building_svg,
  'building-1': building_1_svg,
  cabriolet: cabriolet_svg,
  calculator: calculator_svg,
  calendar: calendar_svg,
  'camping-car': camping_car_svg,
  cancelation: cancelation_svg,
  cancellation: cancellation_svg,
  cancellation_1: cancellation_1_svg,
  car: car_svg,
  'car-hail': car_hail_svg,
  'car-substitution': car_substitution_svg,
  caravan: caravan_svg,
  carelessness: carelessness_svg,
  cars: cars_svg,
  castel: castel_svg,
  chair: chair_svg,
  'change-investments': change_investments_svg,
  channeling: channeling_svg,
  'chat-bubble': chat_bubble_svg,
  'chat-men': chat_men_svg,
  'chat-woman': chat_woman_svg,
  'check-list': check_list_svg,
  cigarette: cigarette_svg,
  citycar: citycar_svg,
  'climate-event': climate_event_svg,
  clock: clock_svg,
  cocktail: cocktail_svg,
  'coffee-machine': coffee_machine_svg,
  coins: coins_svg,
  'coins-dollar': coins_dollar_svg,
  'coins-euro': coins_euro_svg,
  'coins-pound': coins_pound_svg,
  'coins-yen': coins_yen_svg,
  company: company_svg,
  'computer-secure': computer_secure_svg,
  consturction: consturction_svg,
  contamination: contamination_svg,
  contract: contract_svg,
  'contract-termination': contract_termination_svg,
  contractor: contractor_svg,
  conversation: conversation_svg,
  'corrupt-file': corrupt_file_svg,
  'credit-card': credit_card_svg,
  'critical-illness': critical_illness_svg,
  custody: custody_svg,
  danger: danger_svg,
  death: death_svg,
  dental: dental_svg,
  desk: desk_svg,
  desktop: desktop_svg,
  'doctor-man': doctor_man_svg,
  'doctor-woman': doctor_woman_svg,
  document: document_svg,
  dog: dog_svg,
  download: download_svg,
  'electric-car': electric_car_svg,
  'electric-damages': electric_damages_svg,
  'electric-repairing': electric_repairing_svg,
  elevator: elevator_svg,
  employee: employee_svg,
  'employee-hire': employee_hire_svg,
  'employee-retired': employee_retired_svg,
  'employee-transition': employee_transition_svg,
  environment: environment_svg,
  'extractor-hood': extractor_hood_svg,
  eye: eye_svg,
  eye_1: eye_1_svg,
  facebook: facebook_svg,
  family: family_svg,
  'family-g': family_g_svg,
  'family-l': family_l_svg,
  'family-single-f': family_single_f_svg,
  'family-single-m': family_single_m_svg,
  farm: farm_svg,
  fax: fax_svg,
  'financial-loss': financial_loss_svg,
  'financial-loss-2': financial_loss_2_svg,
  'finger-print': finger_print_svg,
  fire: fire_svg,
  'fire-house': fire_house_svg,
  fishing: fishing_svg,
  'flood-house': flood_house_svg,
  floor: floor_svg,
  'food-poisoning': food_poisoning_svg,
  frost: frost_svg,
  fryer: fryer_svg,
  furniture: furniture_svg,
  garage: garage_svg,
  gauge: gauge_svg,
  gear: gear_svg,
  'gear-2': gear_2_svg,
  gender: gender_svg,
  'glas-vitrine': glas_vitrine_svg,
  global: global_svg,
  glossary: glossary_svg,
  'goods-transport': goods_transport_svg,
  'graduation-hat': graduation_hat_svg,
  greenhouse: greenhouse_svg,
  growth: growth_svg,
  'growth-dollar': growth_dollar_svg,
  'growth-euro': growth_euro_svg,
  'growth-pound': growth_pound_svg,
  'growth-yen': growth_yen_svg,
  'hand-cross': hand_cross_svg,
  'hand-heart': hand_heart_svg,
  'hand-leaf': hand_leaf_svg,
  'health-kit': health_kit_svg,
  'hearing-impaired': hearing_impaired_svg,
  heart: heart_svg,
  heater: heater_svg,
  help: help_svg,
  'help-man': help_man_svg,
  'help-woman': help_woman_svg,
  hospital: hospital_svg,
  'hospital-bed': hospital_bed_svg,
  'hotel-bed': hotel_bed_svg,
  'hotel-reception-woman': hotel_reception_woman_svg,
  house: house_svg,
  idcard: idcard_svg,
  inbox: inbox_svg,
  industry: industry_svg,
  'inflammable-liquid': inflammable_liquid_svg,
  injection: injection_svg,
  instagram: instagram_svg,
  'it-vpn': it_vpn_svg,
  keys: keys_svg,
  'laptop-repair': laptop_repair_svg,
  legal: legal_svg,
  'legal-services': legal_services_svg,
  'light-bulb': light_bulb_svg,
  linkedin: linkedin_svg,
  'living-with-parents': living_with_parents_svg,
  'location-image': location_image_svg,
  'magnifer-glass': magnifer_glass_svg,
  mail: mail_svg,
  'major-crisis': major_crisis_svg,
  'man-elderly': man_elderly_svg,
  'man-tie': man_tie_svg,
  'man-woman': man_woman_svg,
  'map--pin-locator': map__pin_locator_svg,
  matchstick: matchstick_svg,
  medal: medal_svg,
  'medical-assistance': medical_assistance_svg,
  men: men_svg,
  'mental-disability': mental_disability_svg,
  merchandise: merchandise_svg,
  microwave: microwave_svg,
  mindset: mindset_svg,
  mobile: mobile_svg,
  'mobile-home': mobile_home_svg,
  moped: moped_svg,
  more: more_svg,
  'motor-disability': motor_disability_svg,
  motorcycle: motorcycle_svg,
  mpv: mpv_svg,
  newspaper: newspaper_svg,
  'note-pen': note_pen_svg,
  'number-of-rooms': number_of_rooms_svg,
  nutrition: nutrition_svg,
  'on-board-device': on_board_device_svg,
  optical: optical_svg,
  organization: organization_svg,
  padlock: padlock_svg,
  'paint-roll': paint_roll_svg,
  pan: pan_svg,
  parking: parking_svg,
  penalty: penalty_svg,
  pet: pet_svg,
  phone: phone_svg,
  'pie-chart': pie_chart_svg,
  'piggy-bank': piggy_bank_svg,
  'pin-locator': pin_locator_svg,
  plane: plane_svg,
  'plaster-crutch': plaster_crutch_svg,
  play: play_svg,
  plug: plug_svg,
  'plug-adaptor': plug_adaptor_svg,
  plus: plus_svg,
  'power-button': power_button_svg,
  print: print_svg,
  'private-mansion': private_mansion_svg,
  'psychological-disability': psychological_disability_svg,
  'public-liability': public_liability_svg,
  puzzle: puzzle_svg,
  questionmark: questionmark_svg,
  radio: radio_svg,
  reffrigerator: reffrigerator_svg,
  register: register_svg,
  'remote-control': remote_control_svg,
  'repair-2': repair_2_svg,
  repairs: repairs_svg,
  'repairs-2': repairs_2_svg,
  restaurant: restaurant_svg,
  ring: ring_svg,
  'road-safety': road_safety_svg,
  'rocking-chair': rocking_chair_svg,
  safe: safe_svg,
  'safety-belt': safety_belt_svg,
  'sail-boat': sail_boat_svg,
  salooncar: salooncar_svg,
  sanitary: sanitary_svg,
  'saving-yen': saving_yen_svg,
  'savings-dollar': savings_dollar_svg,
  'savings-euro': savings_euro_svg,
  'savings-pound': savings_pound_svg,
  'security-cam': security_cam_svg,
  share: share_svg,
  shield: shield_svg,
  'shopping-trolley': shopping_trolley_svg,
  sickness: sickness_svg,
  'site-foreman': site_foreman_svg,
  ski: ski_svg,
  software: software_svg,
  'solar-panel': solar_panel_svg,
  'solid-construction': solid_construction_svg,
  'sports-equipment': sports_equipment_svg,
  store: store_svg,
  strethoscope: strethoscope_svg,
  suitcase: suitcase_svg,
  suitcase_1: suitcase_1_svg,
  sun: sun_svg,
  suv: suv_svg,
  swiss: swiss_svg,
  'symbol-dollar': symbol_dollar_svg,
  'symbol-euro': symbol_euro_svg,
  'symbol-pounds': symbol_pounds_svg,
  'symbol-yen': symbol_yen_svg,
  tablet: tablet_svg,
  target: target_svg,
  taxi: taxi_svg,
  theft: theft_svg,
  thumb: thumb_svg,
  tick: tick_svg,
  time: time_svg,
  tools: tools_svg,
  'town-hall': town_hall_svg,
  tractor: tractor_svg,
  'travel-case': travel_case_svg,
  twitter: twitter_svg,
  umbrella: umbrella_svg,
  upload: upload_svg,
  'usage-type-house': usage_type_house_svg,
  van: van_svg,
  ventilation: ventilation_svg,
  vine: vine_svg,
  'warehouse-fire': warehouse_fire_svg,
  warenhouse: warenhouse_svg,
  'washing-machine': washing_machine_svg,
  'water-can': water_can_svg,
  'water-damage': water_damage_svg,
  wc: wc_svg,
  'weather-warning': weather_warning_svg,
  wechat: wechat_svg,
  wheat: wheat_svg,
  wheelchair: wheelchair_svg,
  'wheelchair-man': wheelchair_man_svg,
  'wind-turbine': wind_turbine_svg,
  'within-1-hrs': within_1_hrs_svg,
  'within-24-hrs': within_24_hrs_svg,
  'within-72-hrs': within_72_hrs_svg,
  woman: woman_svg,
  'woman-elderly': woman_elderly_svg,
  'woman-shirt': woman_shirt_svg,
  world: world_svg,
  youtube: youtube_svg,
};
